### ISSUE TITLE
/opt/nuclio/whl" did not complete successfully

### ISSUE THREAD

**Issue by davy-blavette** [kurkurzz/custom-yolov8-auto-annotation-cvat-blueprint#3]
![image](https://github.com/kurkurzz/custom-yolov8-auto-annotation-cvat-blueprint/assets/3437490/4a6e7e7f-aef1-46ee-8002-fe25110d69f0)

I don't see Where library problem is, any idea ?

./whl/nuclio_sdk-0.5.9-py2.py3-none-any.whl

actually is nuclio-sdk 0.5.10

**Comment by Ekanshh** [comment]
The error says no matching distribution found for msgpack. Maybe try: `pip install msgpack`

**Comment by kurkurzz** [comment]
https://github.com/nuclio/nuclio/issues/3328#issuecomment-2312814815

This might also relevant. Need to set the python runtime to be the same as the base image. In this case it should be `runtime: 'python:3.10'`
