### ISSUE TITLE
Problem with running the docker container

### ISSUE THREAD

**Issue by AnatoliyZabrovskiy** [kurkurzz/custom-yolov8-auto-annotation-cvat-blueprint#5]
Hello!

When I build the docker image and run the container I get this:

24.10.02 06:25:35.632 (D) sor.http.w0.python.logger Running wrapper {"command": "/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --event-socket-path /tmp/nuclio-rpc-crueensp3515d0kt2vig.sock --control-socket-path /tmp/nuclio-rpc-crueensp3515d0kt2vjg.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings"}
{"datetime": "2024-10-02 06:25:35,752", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "No module named 'main'", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 534, in run_wrapper\n    wrapper_instance = Wrapper(root_logger,\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 88, in __init__\n    self._entrypoint = self._load_entrypoint_from_handler(handler)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 331, in _load_entrypoint_from_handler\n    module = __import__(module_name)\nModuleNotFoundError: No module named 'main'\n", "worker_id": "0"}}
{"datetime": "2024-10-02 06:25:35,756", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "No module named 'main'", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 534, in run_wrapper\n    wrapper_instance = Wrapper(root_logger,\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 88, in __init__\n    self._entrypoint = self._load_entrypoint_from_handler(handler)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 331, in _load_entrypoint_from_handler\n    module = __import__(module_name)\nModuleNotFoundError: No module named 'main'\n", "worker_id": "1"}}
24.10.02 06:25:35.771 (E) sor.http.w0.python.logger Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 38 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc000940000)
	/home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:663 +0x434
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper in goroutine 19
	/home/runner/work/nuclio/nuclio/pkg/processor/runtime/rpc/abstract.go:318 +0x1f1

    /nuclio/pkg/platform/local/platform.go:1312
Failed to deploy function
    ...//nuclio/pkg/platform/abstract/platform.go:227

Maybe someone knows how to solve this problem.
Thanks!

--
Best
Anatoliy

**Comment by kurkurzz** [comment]
Sorry I don't know the inside out of CVAT and cannot help you solve that error specifically. but did you cloned the stable release or no? I did the mistake of cloning the "develop" branch and got all these random errors. Perhaps use the stable release branches instead.

**Comment by skyface753** [comment]
I have the same problem. I double checked and I'm not using the develop branch. I also deleted all cvat volumes and started with a fresh setup. But the problem persists

**Comment by skyface753** [comment]
I found the problem. I cloned your repo and adjusted the `spec` in the `function.yaml`. But when deploying the function, the `alternative function and wslcofig/function.yaml` file was used, which include dots in the `spec`. When deleting this file, the deployment works.

**Comment by AnatoliyZabrovskiy** [comment]
> I found the problem. I cloned your repo and adjusted the `spec` in the `function.yaml`. But when deploying the function, the `alternative function and wslcofig/function.yaml` file was used, which include dots in the `spec`. When deleting this file, the deployment works.

Interesting! Thank you! I'll try.

**Comment by AnatoliyZabrovskiy** [comment]
> I found the problem. I cloned your repo and adjusted the `spec` in the `function.yaml`. But when deploying the function, the `alternative function and wslcofig/function.yaml` file was used, which include dots in the `spec`. When deleting this file, the deployment works.

Yes! It works! )

**Comment by kurkurzz** [comment]
@skyface753 Good finding. That folder was a pull request by other user and I havent tested it because assumed everything was ok. kinda weird that it defaulted to that instead of `function.yaml` at root. Will update the repo accordingly.
